G3_gsb_frais_home:
    path:     G3/accueil
    defaults: { _controller: G3GsbFraisBundle:Home:index }
G3_gsb_frais_validerconnexion:
    path:     G3/validerconnexion
    defaults: { _controller: G3GsbFraisBundle:Home:validerconnexion }
G3_gsb_frais_deconnexion:
    path:     G3/deconnexion
    defaults: { _controller: G3GsbFraisBundle:Home:deconnexion }
G3_gsb_frais_listefrais:
    path:     G3/listefrais
    defaults: { _controller: G3GsbFraisBundle:ListeFrais:index }
G3_gsb_frais_saisirfrais:
    path:     G3/saisirfrais
    defaults: { _controller: G3GsbFraisBundle:SaisirFrais:index }
G3_gsb_frais_validerfraishorsforfait:
    path:     G3/validerfraishorsforfait
    defaults: { _controller: G3GsbFraisBundle:SaisirFrais:validerfraishorsforfait }
G3_gsb_frais_supprimerfraishorsforfait:
    path:     G3/supprimerfraishorsforfait/{id}
    defaults: { _controller: G3GsbFraisBundle:SaisirFrais:supprimerfraishorsforfait }